import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { CalendarEvent, CalendarSource } from "../../src/content/events";

function compactEvent(event: CalendarEvent): CalendarEvent {
  const compact: CalendarEvent = {
    id: event.id,
    calendarSlug: event.calendarSlug,
    calendarLabel: event.calendarLabel,
    title: event.title,
    start: event.start,
    end: event.end,
    allDay: event.allDay,
  };

  if (event.description) {
    compact.description = event.description;
  }

  if (event.location) {
    compact.location = event.location;
  }

  return compact;
}

function serializeEvents(events: CalendarEvent[]): string {
  const compacted = events.map(compactEvent);
  return JSON.stringify(compacted, null, 2)
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");
}

function serializeSources(sources: CalendarSource[]): string {
  return JSON.stringify(sources, null, 2)
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");
}

export function writeGeneratedFile(
  sources: CalendarSource[],
  events: CalendarEvent[],
  syncedAt: string,
): void {
  const outputPath = resolve(process.cwd(), "src/content/events.generated.ts");

  const content = `// Generated by pnpm sync:calendar — do not edit manually.
import type { CalendarEvent, CalendarSource } from "./events";

export const syncedAt = ${JSON.stringify(syncedAt)};

export const calendarSources: CalendarSource[] = ${serializeSources(sources)};

export const calendarEvents: CalendarEvent[] = ${serializeEvents(events)};
`;

  writeFileSync(outputPath, content, "utf8");
}
