import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { CalendarEvent, CalendarSource } from "../../src/content/events";

function compactEvent(event: CalendarEvent): CalendarEvent {
  const compact: CalendarEvent = {
    id: event.id,
    calendarSlug: event.calendarSlug,
    calendarLabel: event.calendarLabel,
    title: event.title,
    start: event.start,
    end: event.end,
    allDay: event.allDay,
  };

  if (event.description) {
    compact.description = event.description;
  }

  if (event.location) {
    compact.location = event.location;
  }

  return compact;
}

function serializeEvents(events: CalendarEvent[]): string {
  const compacted = events.map(compactEvent);
  return JSON.stringify(compacted, null, 2)
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");
}

function serializeSources(sources: CalendarSource[]): string {
  return JSON.stringify(sources, null, 2)
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");
}

export function buildGeneratedContent(
  sources: CalendarSource[],
  events: CalendarEvent[],
  syncedAt: string,
): string {
  return `// Generated by pnpm sync:calendar — do not edit manually.
import type { CalendarEvent, CalendarSource } from "./events";

export const syncedAt = ${JSON.stringify(syncedAt)};

export const calendarSources: CalendarSource[] = ${serializeSources(sources)};

export const calendarEvents: CalendarEvent[] = ${serializeEvents(events)};
`;
}

export function contentWithoutSyncedAt(content: string): string {
  return content.replace(
    /^export const syncedAt = .*;\n/m,
    "export const syncedAt = \"<ignored>\";\n",
  );
}

export function writeGeneratedFile(
  sources: CalendarSource[],
  events: CalendarEvent[],
  syncedAt: string,
): boolean {
  const outputPath = resolve(process.cwd(), "src/content/events.generated.ts");
  const content = buildGeneratedContent(sources, events, syncedAt);

  try {
    const existing = readFileSync(outputPath, "utf8");
    if (contentWithoutSyncedAt(existing) === contentWithoutSyncedAt(content)) {
      console.log("No calendar changes; skipping write.");
      return false;
    }
  } catch {
    // File missing — write below.
  }

  writeFileSync(outputPath, content, "utf8");
  return true;
}
